# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Zedboard-Master.xdc

# Block Designs: bd/Task_2_design/Task_2_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task_2_design || ORIG_REF_NAME==Task_2_design} -quiet] -quiet

# IP: bd/Task_2_design/ip/Task_2_design_processing_system7_0_0/Task_2_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task_2_design_processing_system7_0_0 || ORIG_REF_NAME==Task_2_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/Task_2_design/ip/Task_2_design_xbar_0/Task_2_design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task_2_design_xbar_0 || ORIG_REF_NAME==Task_2_design_xbar_0} -quiet] -quiet

# IP: bd/Task_2_design/ip/Task_2_design_ps7_0_axi_periph_0/Task_2_design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task_2_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==Task_2_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Task_2_design/ip/Task_2_design_rst_ps7_0_100M_0/Task_2_design_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task_2_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==Task_2_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Task_2_design/ip/Task_2_design_axi_gpio_0_2/Task_2_design_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task_2_design_axi_gpio_0_2 || ORIG_REF_NAME==Task_2_design_axi_gpio_0_2} -quiet] -quiet

# IP: bd/Task_2_design/ip/Task_2_design_axi_timer_0_0/Task_2_design_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task_2_design_axi_timer_0_0 || ORIG_REF_NAME==Task_2_design_axi_timer_0_0} -quiet] -quiet

# IP: bd/Task_2_design/ip/Task_2_design_sync_0_0/Task_2_design_sync_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task_2_design_sync_0_0 || ORIG_REF_NAME==Task_2_design_sync_0_0} -quiet] -quiet

# IP: bd/Task_2_design/ip/Task_2_design_sync_0_1/Task_2_design_sync_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task_2_design_sync_0_1 || ORIG_REF_NAME==Task_2_design_sync_0_1} -quiet] -quiet

# IP: bd/Task_2_design/ip/Task_2_design_xlconstant_0_0/Task_2_design_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task_2_design_xlconstant_0_0 || ORIG_REF_NAME==Task_2_design_xlconstant_0_0} -quiet] -quiet

# IP: bd/Task_2_design/ip/Task_2_design_axi_gpio_0_3/Task_2_design_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task_2_design_axi_gpio_0_3 || ORIG_REF_NAME==Task_2_design_axi_gpio_0_3} -quiet] -quiet

# IP: bd/Task_2_design/ip/Task_2_design_auto_pc_0/Task_2_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task_2_design_auto_pc_0 || ORIG_REF_NAME==Task_2_design_auto_pc_0} -quiet] -quiet

# XDC: /home/christophlehr/TUWien/studium/es_fpga/VU_ES_FPGA/Zynq/vivado_workspace/Task_2/Task_2.gen/sources_1/bd/Task_2_design/Task_2_design_ooc.xdc
