# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/christophlehr/TUWien/studium/es_fpga/digilent-xdc-master/Zedboard-Master.xdc

# Block Designs: bd/Task_1_design/Task_1_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task_1_design || ORIG_REF_NAME==Task_1_design} -quiet] -quiet

# IP: bd/Task_1_design/ip/Task_1_design_processing_system7_0_0/Task_1_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task_1_design_processing_system7_0_0 || ORIG_REF_NAME==Task_1_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/Task_1_design/ip/Task_1_design_axi_gpio_0_0/Task_1_design_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task_1_design_axi_gpio_0_0 || ORIG_REF_NAME==Task_1_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Task_1_design/ip/Task_1_design_axi_gpio_0_1/Task_1_design_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task_1_design_axi_gpio_0_1 || ORIG_REF_NAME==Task_1_design_axi_gpio_0_1} -quiet] -quiet

# IP: bd/Task_1_design/ip/Task_1_design_proc_sys_reset_0_0/Task_1_design_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task_1_design_proc_sys_reset_0_0 || ORIG_REF_NAME==Task_1_design_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/Task_1_design/ip/Task_1_design_xbar_0/Task_1_design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task_1_design_xbar_0 || ORIG_REF_NAME==Task_1_design_xbar_0} -quiet] -quiet

# IP: bd/Task_1_design/ip/Task_1_design_ps7_0_axi_periph_0/Task_1_design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task_1_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==Task_1_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Task_1_design/ip/Task_1_design_xlconstant_0_0/Task_1_design_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task_1_design_xlconstant_0_0 || ORIG_REF_NAME==Task_1_design_xlconstant_0_0} -quiet] -quiet

# IP: bd/Task_1_design/ip/Task_1_design_util_vector_logic_0_0/Task_1_design_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task_1_design_util_vector_logic_0_0 || ORIG_REF_NAME==Task_1_design_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/Task_1_design/ip/Task_1_design_sync_0_0/Task_1_design_sync_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task_1_design_sync_0_0 || ORIG_REF_NAME==Task_1_design_sync_0_0} -quiet] -quiet

# IP: bd/Task_1_design/ip/Task_1_design_auto_pc_0/Task_1_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task_1_design_auto_pc_0 || ORIG_REF_NAME==Task_1_design_auto_pc_0} -quiet] -quiet

# XDC: /home/christophlehr/TUWien/studium/es_fpga/VU_ES_FPGA/Zynq/vivado_workspace/Task_1/Task_1.gen/sources_1/bd/Task_1_design/Task_1_design_ooc.xdc
