# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/christophlehr/TUWien/studium/es_fpga/VU_ES_FPGA/Zynq/vivado_workspace/Task_2/Task_2.srcs/sources_1/bd/Task_2_design/ip/Task_2_design_xbar_0/Task_2_design_xbar_0.xci
# IP: The module: 'Task_2_design_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/christophlehr/TUWien/studium/es_fpga/VU_ES_FPGA/Zynq/vivado_workspace/Task_2/Task_2.gen/sources_1/bd/Task_2_design/ip/Task_2_design_xbar_0/Task_2_design_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Task_2_design_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/christophlehr/TUWien/studium/es_fpga/VU_ES_FPGA/Zynq/vivado_workspace/Task_2/Task_2.srcs/sources_1/bd/Task_2_design/ip/Task_2_design_xbar_0/Task_2_design_xbar_0.xci
# IP: The module: 'Task_2_design_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/christophlehr/TUWien/studium/es_fpga/VU_ES_FPGA/Zynq/vivado_workspace/Task_2/Task_2.gen/sources_1/bd/Task_2_design/ip/Task_2_design_xbar_0/Task_2_design_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Task_2_design_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
